class Phrases:
    phrases = [
        "Cursed Technique: Mark Rober Glitter Bomb",
        "With this sacred treasure I summon: A mentally unstable woman",
        "Domain expansion: Pouring cooking oil down the drain",
        "Domain expansion: Alt + F4",
        "Domain expansion: hepatitis B",
        "With this sacred treasure I summon: Lebron James",
        "Imaginary technique: Outpizza the hut",
        "With this treasure I summon: iPad kid in a fancy restaurant",
        "Domain expansion: Indian street food",
        "With this sacred treasure I summon: Matpat",
        "Cursed speech technique: L + ratio",
        "With this sacred treasure I summon: the real slim shady",
        "Domain Expansion: Airplane mode during a phone call",
        "Cursed Technique: Unskippable YouTube ad",
        "With this sacred treasure I summon: 3 AM existential crisis",
        "Imaginary Technique: Double texting without a reply",
        "Domain Expansion: Auto-playing Netflix episodes",
        "With this treasure I summon: The last slice of pizza",
        "Domain Expansion: Your Uber driver missing the turn",
        "Cursed Speech Technique: Saying 'We need to talk'",
        "With this sacred treasure I summon: Wifi that disconnects at 99% download",
        "Imaginary Technique: Watching one more episode before bed",
        "Cursed Technique: Seeing your screen reflection while binge-watching",
        "With this treasure I summon: A toddler with sticky hands",
        "Imaginary Technique: Forgetting why you walked into a room",
        "With this sacred treasure I summon: A cat who knocks things off tables",
        "Domain Expansion: Leaving your charger at home",
        "Cursed Speech Technique: 'It’s not you, it’s me'",
        "With this treasure I summon: An iPhone on 1% battery",
        "Domain Expansion: Stepping on a Lego barefoot",
        "Domain Expansion: Arson",
        "With this treasure I summon: Someone who always sends voice notes",
        "Imaginary Technique: Leaving the gas station without your wallet",
        "Domain expansion: farting but it wasn't actually a fart",
        "Domain Expansion: the cheese touch",
        "Imaginary technique: financial stability",
        "Imaginary technique: Escaping the Friend Zone",
        "Cursed technique: Burger King foot lettuce",
        "With this sacred treasure I summon: My dad",
        "Cursed speech technique: ur mom",
        "Imaginary technique: father figure",
        "Domain Expansion: DMV",
        "Domain Expansion: O-Block",
        "Domain Expansion: Haunted house while on psychedelics",
        "Cursed speech technique: blink manually",
        "PURPLE🟣",
        "Domain Expansion: rule 34",
        "Reverse cursed technique: backshots",
        "Domain expansion: Diddy party",
        "With this treasure I summon: P-Diddy",
        "With this treasure I summon: Osama Bin Laden",
        "Domain expansion: 9/11",
        "Domain Expansion: The year 2020",
        "Imaginary technique: schizophrenia",
        "Domain Expansion: The casting couch",
        "Domain Expansion: Florida",
        "Domain Expansion: TSA random search",
        "With this sacred treasure I summon: Michelle Obama",
        "Cursed technique: HIV",
        "Cursed Technique: Emotional detachment",
        "With this sacred treasure I summon: Lifelong regret",
        "Imaginary Technique: Ignoring red flags",
        "Domain Expansion: Self-sabotage",
        "Domain Expansion: Missed opportunities",
        "Cursed Technique: Apologizing for something you didn't do",
        "With this sacred treasure I summon: A void where empathy used to be",
        "Imaginary Technique: Drowning in debt",
        "Cursed Technique: Unspoken family trauma",
        "Imaginary Technique: Disappearing into obscurity",
        "Cursed Technique: Pretending everything is fine"
    ]
